
name: ebean-test-docker EA

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '48 8 * * 1,3,5'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        java_version: [GA,EA] ## valhalla,metropolis,panama
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net
        release: ${{ matrix.java_version }}
    - name: Maven cache
      uses: actions/cache@v2
      env:
        cache-name: maven-cache
      with:
        path:
          ~/.m2
        key: build-${{ env.cache-name }}
    - name: Build with Maven
      run: mvn clean test

